"""Add avatar_url + status to users

Revision ID: 4355377394c9
Revises: 8e8a42f346c0
Create Date: 2025-12-05 09:13:28.163950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4355377394c9'
down_revision: Union[str, Sequence[str], None] = '8e8a42f346c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_actions_id'))

    op.drop_table('workflow_actions')
    with op.batch_alter_table('workflow_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_triggers_id'))

    op.drop_table('workflow_triggers')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('avatar_url')

    op.create_table('workflows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_id'), ['id'], unique=False)

    op.create_table('workflow_triggers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('config_json', mysql.JSON(), nullable=True),
    sa.Column('conditions_json', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_triggers_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('workflow_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_triggers_id'), ['id'], unique=False)

    op.create_table('workflow_actions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_index', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('config_json', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_actions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_actions_id'), ['id'], unique=False)

    # ### end Alembic commands ###
