"""fix ai_settings

Revision ID: 4629324b2252
Revises: 
Create Date: 2025-11-15 13:24:20.155824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4629324b2252'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('api_provider')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('draft', 'active', 'completed', 'archived', name='campaignstatus'),
               existing_nullable=True)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'DE'"))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_id'), ['id'], unique=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('tax_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'sent', 'paid', 'cancelled', 'overdue', 'reminder', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'draft'"))

    with op.batch_alter_table('pbx_settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('api_url',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('api_key',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('sip_password',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('id'))
        batch_op.create_index(batch_op.f('ix_pbx_settings_id'), ['id'], unique=False)
        batch_op.drop_column('company_id')
        batch_op.drop_column('webhook_url')

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.ENUM('admin', 'mitarbeiter', 'kunde', collation='utf8mb4_unicode_ci'), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_id'))

    with op.batch_alter_table('pbx_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_pbx_settings_id'))
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('sip_password',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('api_key',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('api_url',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'sent', 'paid', 'cancelled', 'overdue', 'reminder', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'draft'"))

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('tax_rate',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('unit_price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_id'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('country',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'DE'"))
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'active', 'completed', 'archived', name='campaignstatus'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)

    with op.batch_alter_table('ai_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model')
        batch_op.drop_column('provider')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
