"""add companies table

Revision ID: e192d6891976
Revises: b7e6cf1d49c5
Create Date: 2025-11-28 12:10:30.717290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e192d6891976'
down_revision: Union[str, Sequence[str], None] = 'b7e6cf1d49c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('workflow_triggers')
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_actions_id'))

    op.drop_table('workflow_actions')
    op.drop_table('workflows')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customer_company'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer_companies', ['company_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('uploaded_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('email_providers', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_index(batch_op.f('ix_email_providers_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_providers_id'))
        batch_op.alter_column('is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_id'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('uploaded_by',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_customer_company'), 'customer_companies', ['company_id'], ['id'], ondelete='SET NULL')

    op.create_table('workflows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('workflow_actions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_index', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('config_json', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_actions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_actions_id'), ['id'], unique=False)

    op.create_table('workflow_triggers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('config_json', mysql.JSON(), nullable=True),
    sa.Column('conditions_json', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_triggers_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
